[package]
name = "blaze-jni-bridge"
version = "0.1.0"
edition = "2021"
resolver = "1"

[dependencies]
datafusion = { workspace = true }
jni = "0.20.0"
log = "0.4.22"
once_cell = "1.20.2"
paste = "1.0.15"
