[package]
name = "blaze-jni-bridge"
version = "0.1.0"
edition = "2024"
resolver = "1"

[dependencies]
datafusion = { workspace = true }
jni = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
paste = { workspace = true }
