[package]
name = "blaze-rs"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
datafusion = "6.0.0"
env_logger = "0.9.0"
jni = "0.19.0"
log = "0.4.14"
prost = "0.9.0"
tokio = "1.15.0"
datafusion-ext = { path = "datafusion-ext" }
plan-serde = { path = "plan-serde" }

[patch.crates-io]
datafusion = { git = "https://github.com/blaze-init/arrow-datafusion.git", branch = "bz_master"}
arrow = { git = "https://github.com/apache/arrow-rs.git", branch = "master" }
parquet = { git = "https://github.com/apache/arrow-rs.git", branch = "master" }

[profile.dev]
overflow-checks = false
