[package]
name = "datafusion-ext-plans"
version = "0.1.0"
edition = "2021"
resolver = "1"

[features]
default = ["tokio/rt-multi-thread"]

[dependencies]
arrow = { workspace = true }
async-trait = "0.1.77"
base64 = "0.21.7"
bytes = "1.4.0"
blaze-jni-bridge = { workspace = true }
bytesize = "1.1.0"
datafusion = { workspace = true }
datafusion-ext-commons = { workspace = true }
datafusion-ext-exprs = { workspace = true }
derivative = "2.2.0"
futures = "0.3"
gxhash = "3.1.0"
hashbrown = "0.14.3"
itertools = "0.10.3"
jni = "0.20.0"
log = "0.4.14"
lz4_flex = "0.11.2"
num = "0.4.0"
object_store = "0.6.1"
once_cell = "1.19.0"
panic-message = "0.3.0"
parking_lot = "0.12.1"
paste = "1.0.7"
slimmer_box = "0.6.5"
smallvec = "1.13.1"
tempfile = "3"
tokio = "1.36"
uuid = "1.7.0"
zstd = "0.12.3"