name: TPC-DS

on:
  workflow_dispatch:
  push:

jobs:
  test-spark303:
    name: Test Spark303
    uses: ./.github/workflows/tpcds-reusable.yml
    with:
      sparkver: spark303
      sparkurl: https://archive.apache.org/dist/spark/spark-3.0.3/spark-3.0.3-bin-hadoop2.7.tgz

  test-spark313:
    name: Test Spark313
    uses: ./.github/workflows/tpcds-reusable.yml
    with:
      sparkver: spark313
      sparkurl: https://archive.apache.org/dist/spark/spark-3.1.3/spark-3.1.3-bin-hadoop2.7.tgz

  test-spark320:
    name: Test Spark320
    uses: ./.github/workflows/tpcds-reusable.yml
    with:
      sparkver: spark320
      sparkurl: https://archive.apache.org/dist/spark/spark-3.2.0/spark-3.2.0-bin-hadoop2.7.tgz

  test-spark324:
    name: Test Spark324
    uses: ./.github/workflows/tpcds-reusable.yml
    with:
      sparkver: spark324
      sparkurl: https://archive.apache.org/dist/spark/spark-3.2.4/spark-3.2.4-bin-hadoop2.7.tgz

  test-spark333:
    name: Test Spark333
    uses: ./.github/workflows/tpcds-reusable.yml
    with:
      sparkver: spark333
      sparkurl: https://archive.apache.org/dist/spark/spark-3.3.3/spark-3.3.3-bin-hadoop3.tgz

  test-spark351:
    name: Test Spark351
    uses: ./.github/workflows/tpcds-reusable.yml
    with:
      sparkver: spark351
      sparkurl: https://archive.apache.org/dist/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz
