name: TPC-DS-Celeborn-Reusable

on:
  workflow_call:
    inputs:
      celebornver:
        required: true
        type: string
      celebornurl:
        required: true
        type: string

jobs:
  test-spark-35-celeborn:
    name: Test spark-3.5 celeborn-${{ inputs.celebornver }}
    uses: ./.github/workflows/tpcds-reusable.yml
    with:
      sparkver: spark-3.5
      sparkurl: https://archive.apache.org/dist/spark/spark-3.5.6/spark-3.5.6-bin-hadoop3.tgz
      celebornver: ${{ inputs.celebornver }}
      celebornurl: ${{ inputs.celebornurl }}
      extrablazebuildopt: -Pceleborn-${{ inputs.celebornver }} -DcelebornScope=compile
      extrablazeidentifier: celeborn-${{ inputs.celebornver }}
      extrasparkconf: >-
        --conf spark.shuffle.manager=org.apache.spark.sql.execution.blaze.shuffle.celeborn.BlazeCelebornShuffleManager
        --conf spark.serializer=org.apache.spark.serializer.KryoSerializer
        --conf spark.celeborn.client.spark.shuffle.writer=hash
        --conf spark.celeborn.client.push.replicate.enabled=false
