name: TPC-DS Reusable

on:
  workflow_call:
    inputs:
      sparkver:
        required: true
        type: string
      sparkurl:
        required: true
        type: string

jobs:
  build-validator:
    name: Build Validator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v4
        id: cache-tpcds-validator
        with:
          key: tpcds-validator
          path: target/tpcds-validator_2.12-0.1.0-SNAPSHOT-with-dependencies.jar

      - uses: actions/checkout@v4
        if: steps.cache-tpcds-validator.outputs.cache-hit != 'true'
        with:
          repository: blaze-init/tpcds-validator

      - uses: actions/setup-java@v4
        if: steps.cache-tpcds-validator.outputs.cache-hit != 'true'
        with:
          distribution: 'adopt-hotspot'
          java-version: '8'
          cache: 'maven'

      - name: Build
        if: steps.cache-tpcds-validator.outputs.cache-hit != 'true'
        run: mvn package -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tpcds-validator-${{ inputs.sparkver }}
          path: target/tpcds-validator_2.12-0.1.0-SNAPSHOT-with-dependencies.jar
          overwrite: true

  build-blaze-jar:
    name: Build Blaze JAR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt-hotspot'
          java-version: '8'
          cache: 'maven'

      - uses: arduino/setup-protoc@v2
        with: {version: "21.7"}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          rustflags: --allow warnings -C target-feature=+aes
          components:
            cargo
            rustfmt

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

      - name: Cargo test
        run: cargo +nightly test --workspace --all-features

      - name: Build ${{ inputs.sparkver }}
        run: mvn package -Ppre -P${{ inputs.sparkver }}

      - name: Upload ${{ inputs.sparkver }}
        uses: actions/upload-artifact@v4
        with:
          name: blaze-engine-${{ inputs.sparkver }}
          path: target/blaze-engine-${{ inputs.sparkver }}-pre-*-SNAPSHOT.jar
          overwrite: true

  run-tpcds-test:
    name: Run TPC-DS test ${{ matrix.query }}
    needs: [build-validator, build-blaze-jar]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        query: [
          q1,q2,q3,q4,q5,q6,q7,q8,q9,
          q10,q11,q12,q13,q14a,q14b,q15,q16,q17,q18,q19,
          q20,q21,q22,q23a,q23b,q24a,q24b,q25,q26,q27,q28,q29,
          q31,q33,q34,q35,q36,q37,q38,q39a,q39b,
          q40,q41,q42,q43,q44,q45,q46,q47,q48,q49,
          q50,q51,q52,q53,q54,q55,q56,q57,q58,q59,
          q60,q61,q62,q63,q64,q65,q66,q67,q68,q69,
          q70,q71,q72,q73,q74,q75,q76,q77,q78,q79,
          q80,q81,q82,q83,q84,q85,q86,q87,q88,q89,
          q90,q91,q92,q93,q94,q95,q96,q97,q98,q99
        ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache-spark-bin
        with:
          path: spark-bin-${{ inputs.sparkver }}
          key: spark-bin-${{ inputs.sparkver }}

      - name: Setup ${{ inputs.sparkver }}
        id: setup-spark-bin
        if: steps.cache-spark-bin.outputs.cache-hit != 'true'
        run: |
          wget -c ${{ inputs.sparkurl }}
          mkdir -p spark-bin-${{ inputs.sparkver }}
          cd spark-bin-${{ inputs.sparkver }} && tar -xf ../spark-*.tgz --strip-component=1

      - uses: actions/download-artifact@v4
        with:
          name: blaze-engine-${{ inputs.sparkver }}

      - uses: actions/download-artifact@v4
        with:
          name: tpcds-validator-${{ inputs.sparkver }}

      - name: Checkout TPC-DS Data
        uses: actions/checkout@v4
        with:
          repository: blaze-init/tpcds_1g
          path: dev/tpcds_1g

      - name: Install Blaze JAR
        run: |
          ls -la
          cp blaze-engine-*${{ inputs.sparkver }}*.jar spark-bin-${{ inputs.sparkver }}/jars/

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt-hotspot'
          java-version: '8'
          cache: 'maven'

      - name: Run
        run: |
          ls -la
          export RUST_LOG=ERROR
          export RUST_BACKTRACE=1
          SPARK_HOME=spark-bin-${{ inputs.sparkver }} dev/run-tpcds-test \
            --data-location dev/tpcds_1g \
            --query-filter ${{ matrix.query }}
